name: "Label Previous Pull Requests"
on:
    schedule:
        - cron: 1 * * * *

jobs:
    labeler:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:

            # Label PRs 1, 2, and 3
            - uses: actions/labeler@v5
              with:
                  pr-number: |
                      1
                      2
                      3
