name: "Label Previous Pull Requests"
on:
    schedule:
        - cron: '1 * * * *'

jobs:
    labeler:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@v5
